name: Python Unit Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.py"
  push:
    branches:
      - main
      - next
    paths:
      - "**.py"

env:
  python-version: "3.11"

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v5

      - name: Run Python tests
        uses: ./.github/actions/tests/python
        with:
          environment: "local"
          python-version: "${{ env.python-version}}"
          openai-api-organization: "${{ secrets.OPENAI_API_ORGANIZATION }}"
          openai-api-key: "${{ secrets.OPENAI_API_KEY }}"
          mysql-host: "${{ secrets.MYSQL_HOST }}"
          mysql-port: "${{ secrets.MYSQL_PORT }}"
          mysql-user: "${{ secrets.MYSQL_USER }}"
          mysql-password: "${{ secrets.MYSQL_PASSWORD }}"
          mysql-database: "${{ secrets.MYSQL_DATABASE }}"
          mysql-charset: "${{ secrets.MYSQL_CHARSET }}"
          codecov-token: "${{ secrets.CODECOV_TOKEN }}"
